kind: Service
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  type: NodePort
  ports:
    - port: 8089
      targetPort: loc-master-web
      name: loc-master-web
      nodePort: 30089
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
      nodePort: 30057
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
      nodePort: 30058
  selector:
    name: locust
    role: master
